version: 2
jobs:
  build:
    docker:
      - image: circleci/php:7.0-apache-stretch-node-browsers
    steps:
      - checkout
      - run: composer require phpunit/phpunit
      - run: ./vendor/bin/phpunit test/

